export const ADD_TO_CART = "ADD_TO_CART";
export const REMOVE_FROM_CART = "REMOVE_FROM_CART";
export const ORDER_PRICES = "ORDER_PRICES";
export const SORT_PRODUCT_BY_SIZES = "SORT_PRODUCT_BY_SIZES";
